### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by The5-1** [Illation/ETEngine#40]
Many of the engine projects on github launch discord servers lately.
How about one for ETEngine too?

**Comment by Illation** [comment]
Yeah why not, I'll make one in a bit. I was intending to create one once I deem the engine to be usable - probably two releases from now. But I guess it won't hurt to have a place to talk about it before for those who don't mind the pre release state of things.

**Comment by Illation** [comment]
Aaand it's done: https://discord.gg/zq6QhvEb
