### ISSUE TITLE
Outdated Cmake commands

### ISSUE THREAD

**Issue by The5-1** [Illation/ETEngine#41]
Nothing big but `-H. -Bbuild` is apparently deprecated since 3.13. Its `-S . - B build` now.
Since the -H is apparently not documented it took me a while to figure out what the intend was.
https://stackoverflow.com/questions/11143062/getting-cmake-to-build-out-of-source-without-wrapping-scripts

Not urgent or anything seeing how you are still winding up to a release.
Just documenting.

**Comment by Illation** [comment]
Yup I tested that and it works. Updated build docs. https://github.com/Illation/ETEngine/commit/dd2c00ebb44d2b7cfdaa01daa669b3ff008c2930
