### ISSUE TITLE
Font buffer size is being calculated incorrectly

### ISSUE THREAD

**Issue by ajweeks** [Illation/ETEngine#6]
I believe the following lines should not take into account the number of elements in the `TextVertex` struct, but rather simply store the current number of `tVerts`. 

https://github.com/Illation/ETEngine/blob/13f203b6731ca9c61f724234e1b30c06d48655a2/source/Engine/GraphicsHelper/TextRenderer.cpp#L168
https://github.com/Illation/ETEngine/blob/13f203b6731ca9c61f724234e1b30c06d48655a2/source/Engine/GraphicsHelper/TextRenderer.cpp#L209

E.g, the correct code would be

```
pFont->m_BufferStart = (int32)tVerts.size();
```

and

```
pFont->m_BufferSize = ((int32)tVerts.size()) - pFont->m_BufferStart;
```

**Comment by Illation** [comment]
The old text renderer was removed in favour of GUI rendering through RmlUI and imgui
